create table departamento (
  id     bigint generated by default as identity,
  nombre varchar(255) not null,
  primary key (id)
);
create table estudiante (
  id              bigint generated by default as identity,
  direccion       varchar(255) not null,
  email           varchar(255) not null,
  nombre          varchar(255) not null,
  telefono        varchar(255) not null,
  departamento_id bigint,
  usuario_id      bigint,
  primary key (id)
);
create table profesor (
  id         bigint generated by default as identity,
  cargo      varchar(255) not null,
  nombre     varchar(255) not null,
  usuario_id bigint       not null,
  primary key (id)
);
create table rol (
  id          bigint       not null,
  descripcion varchar(255) not null,
  nombre      varchar(255) not null,
  primary key (id)
);
create table usuario (
  id       bigint generated by default as identity,
  login    varchar(255)      not null,
  password varchar(255)      not null,
  enabled  bool default true not null,
  primary key (id)
);
create table usuario_roles (
  usuario_id bigint not null,
  roles_id   bigint not null,
  primary key (usuario_id, roles_id)
);
alter table estudiante
  add constraint FKgy0vpfv1vyewg7xv19h8d8ado
foreign key (departamento_id)
references departamento;
alter table estudiante
  add constraint FKs6tki8rbjso4kwof8pdlfufow
foreign key (usuario_id)
references usuario;
alter table profesor
  add constraint FKcmfic78v0qp2wu3c0n9jbqhox
foreign key (usuario_id)
references usuario;
alter table usuario_roles
  add constraint FK861wr18rjyh6pmadvor1u36vb
foreign key (roles_id)
references rol;
alter table usuario_roles
  add constraint FKqblnumndby0ftm4c7sg6uso6p
foreign key (usuario_id)
references usuario;
